services:
  - type: web
    name: prism
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci --include=dev && npm run db:migrate:prod && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: INGEST_API_KEY
        sync: false
      - key: PH_TOKEN
        sync: false
